version: "3.9"

services:
  db:
    image: postgres:17
    container_name: car_db
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: car_scraper
    env_file:
      - .env
    volumes:
      - ./dumps:/app/dumps
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pg_data:
